### ISSUE TITLE
Highlight annotations `new` value

### ISSUE THREAD

**Issue by glmdgrielson** [afrmtbl/annotationlib#5]
The `highlight` type annotations should be able to open links in a new window. I know this was used in [this video](https://dev.invidio.us/watch?v=n0S2r_c6Waw) and it's hampered by the lack of it.

**Comment by afrmtbl** [comment]
Addressed by b800a9dab4c15db8cbe07b96d50ee5b5018541c7 and 9982f765d176370e30ef19875dd9f3697a48db9a
